# Generated by Django 5.1.6 on 2025-02-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
