# Generated by Django 5.1.6 on 2025-04-16 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0006_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.department'),
        ),
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.course'),
        ),
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.department'),
        ),
        migrations.AlterField(
            model_name='post',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='uniapp.faculty'),
        ),
        migrations.AlterField(
            model_name='post',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.semester'),
        ),
        migrations.AlterField(
            model_name='savedpost',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to='uniapp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.semester'),
        ),
    ]
