# Generated by Django 5.1.6 on 2025-04-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0007_alter_admin_department_alter_post_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message',
        ),
    ]
