# Generated by Django 5.1.6 on 2025-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0008_remove_post_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
