# Generated by Django 5.1.6 on 2025-04-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0009_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
