# Generated by Django 5.1.6 on 2025-04-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0010_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
