# Generated by Django 5.1.6 on 2025-05-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0011_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='Faculty', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='add Course name', max_length=100),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Subject', max_length=100)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='uniapp.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='uniapp.semester')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uniapp.subject'),
        ),
    ]
