# Generated by Django 5.1.6 on 2025-05-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0012_admin_name_faculty_name_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
