# Generated by Django 5.1.6 on 2025-06-17 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0013_alter_post_document_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source_url', models.URLField(unique=True)),
                ('source_name', models.CharField(max_length=50)),
                ('raw_content', models.TextField()),
                ('tag_suggestions', models.JSONField(default=list)),
                ('published_at', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('prompts', models.JSONField(blank=True, default=list)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniapp.department')),
            ],
        ),
    ]
