# Generated by Django 5.1.6 on 2025-06-24 11:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0014_articlestaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestaging',
            name='prompts',
        ),
        migrations.AddField(
            model_name='articlestaging',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlestaging',
            name='generated_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlestaging',
            name='summary',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
