# Generated by Django 5.1.6 on 2025-07-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0015_remove_articlestaging_prompts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleStaging',
        ),
    ]
