# Generated by Django 5.1.6 on 2025-07-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0016_delete_articlestaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Machine Learning & AI', 'Machine Learning & AI'), ('Software Engineering', 'Software Engineering'), ('Systems & Networks', 'Systems & Networks'), ('Cybersecurity', 'Cybersecurity'), ('Human-Computer Interaction', 'Human-Computer Interaction'), ('Data Science & Analytics', 'Data Science & Analytics'), ('Emerging Technologies', 'Emerging Technologies')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Research Major',
                'verbose_name_plural': 'Research Majors',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='majors',
            field=models.ManyToManyField(blank=True, related_name='faculty_members', to='uniapp.researchmajor'),
        ),
    ]
