# Generated by Django 5.1.6 on 2025-07-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source_url', models.URLField(unique=True)),
                ('source_name', models.CharField(max_length=50)),
                ('raw_content', models.TextField()),
                ('tag_suggestions', models.JSONField(default=list)),
                ('published_at', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('prompts', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='FeedUpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('google_id', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
