# Generated by Django 5.1.6 on 2025-07-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedupuser',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='feedup.articlestaging'),
        ),
    ]
