# Generated by Django 5.1.6 on 2025-07-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedup', '0002_feedupuser_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedupuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feedupuser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
