# Generated by Django 5.1.6 on 2025-07-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedup', '0003_alter_feedupuser_google_id_alter_feedupuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedupuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
