# Generated by Django 5.1.6 on 2025-07-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedup', '0006_remove_feedupuser_bookmarks_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source_url', models.URLField(unique=True)),
                ('source_name', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('prompts', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField()),
                ('staging_article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedup.articlestaging')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='feedup.article'),
        ),
    ]
