# Generated by Django 5.1.6 on 2025-07-08 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedup', '0007_article_alter_bookmark_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlestaging',
            options={'ordering': ['-published_at']},
        ),
    ]
