# Generated by Django 5.1.6 on 2025-07-12 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedup', '0009_airesponsebookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponsebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_bookmarks', to='feedup.feedupuser'),
        ),
    ]
