# Generated by Django 5.1.6 on 2025-07-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedup', '0010_alter_airesponsebookmark_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('website_url', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline_submission', models.DateField(blank=True, null=True)),
                ('deadline_notification', models.DateField(blank=True, null=True)),
                ('topics', models.TextField(blank=True, null=True)),
                ('unique_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date'], name='feedup_conf_start_d_97d6df_idx'), models.Index(fields=['source', 'source_id'], name='feedup_conf_source_68b5a6_idx'), models.Index(fields=['unique_hash'], name='feedup_conf_unique__50a0b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResearchUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('publication_date', models.DateField()),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publication_date'],
                'indexes': [models.Index(fields=['-publication_date'], name='feedup_rese_publica_de7750_idx'), models.Index(fields=['source', 'source_id'], name='feedup_rese_source_a5c3da_idx'), models.Index(fields=['unique_hash'], name='feedup_rese_unique__7589a9_idx')],
            },
        ),
    ]
