# Generated by Django 5.1.6 on 2025-07-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedup', '0011_conference_researchupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchupdate',
            name='search_category',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
    ]
